### ISSUE TITLE
Creature Level Scaling

### ISSUE THREAD

**Issue by talamortis** [azerothcore/mod-vas-autobalance#1]
Creature Scaling in world does not work for creatures in higher zones, go to strangle thorn vale at level 1 and all creatures are max level.

Also if two players enter a dungeon/raid the creature uses the same level at the 1st person who attacks it. so if a level 1 attacks it all the creatures hp points/level/damage will be for level 1 instead of doing percentages or players hp

**Comment by Yehonal** [comment]
Yes it is not intended to work in this way but could be implemented. For
now it is only scaled from low to higher

Il 25 Feb 2018 00:27, "Lee" <notifications@github.com> ha scritto:
