### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-vas-autobalance#22]
When you enter dungeon alone, scaling is a bit lower, so Raid bosses can be soloed.
That can be sorted with config, to increase scaling numbers.

But then, real problem is when you have, let's say 6 players in Naxxramas, where boss have more health and damage then hes supposed to have even on 10man.

Same happen in dungeons.
For example, Azure Warder NPC (Link bellow) on HC, with 3 players inside have 69k hp, while default with 5 players is 57.

I tried to work with config, to disable ID's as well but there's no proper solution.

Balance is good, but only for, let's say "Singe player" experience.

https://www.wowhead.com/npc=26716/azure-warder

**Comment by disclosurez** [comment]
this works for me:

VASAutoBalance.InflectionPoint=0.2
VASAutoBalance.numPlayer=3
VASAutoBalance.MinDamageModifier=0.3
VASAutoBalance.MinHPModifier=0.04

**Comment by milestorme** [comment]
VASAutoBalance.levelUseDbValuesWhenExists = 0
VASAutoBalance.LevelEndGameBoost = 1

I think these 2 settings are designed to stop the infinite scaling over dB values . Try playing with them to see if you can stop it overscaling

**Comment by BarbzYHOOL** [comment]
"When you enter dungeon alone, scaling is a bit lower, so Raid bosses can be soloed."

isn't it the desired result?
