### ISSUE TITLE
Mod doesn't load

### ISSUE THREAD

**Issue by DogusDE** [azerothcore/mod-vas-autobalance#24]
Hey there, 

the mod doesn't load at startup of my server. There is no output in the log or somewhere else, so i have no idea what's wrong. 
I uploaded it, rerun 

cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wowi/azeroth-server/

than there was created a new folder in the azerothcore mod-folder, with a conf.dist-file which i cp'd to a regular .config-file, edited it and restartet the server. Whatever we tried to edit, there is no change at all. The NPCs doesn't scale.

Just to be clear for me, because it's the first mod i try to install ever: 
I just have to rerun the cmake line, not the commands "make -j" and "make install", rigth? 

Thx for help.

**Comment by milestorme** [comment]
So you have 2 copies of the conf eg .conf.dist and .conf , enable vas in the conf to be set to 1 for dungeons and raids , and cmake with scripts 1
`cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wowi/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1`

**Comment by DogusDE** [comment]
Thanks for the answere :) 
Doesn't work ... 

Thats the output: 

`root@s18299369:/home/wowi/azerothcore/build# cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wowi/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1
Loading module: modules/mod-vas-autobalance-master
-- Running cmake hook: AFTER_LOAD_CONF
-- No hooks registered for AFTER_LOAD_CONF
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: Enabled c++14 support
-- GCC: Enabled C99 support
-- GCC: SFMT enabled, SSE2 flags forced
-- Running cmake hook: AFTER_LOAD_CMAKE_MODULES
-- No hooks registered for AFTER_LOAD_CMAKE_MODULES
-- cotire 1.8.0 loaded.
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadbclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found git binary : /usr/bin/git

* AzerothCore revision            : 490fd16bf56d+ 2019-05-27 12:09:40 +0000 (master branch)
* AzerothCore buildtype           : Release

* Install core to                 : /home/wowi/azeroth-server
* Install libraries to            : /home/wowi/azeroth-server/lib
* Install configs to              : /home/wowi/azeroth-server/etc

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use unix gperftools             : No  (default)
* Use GIT revision hash           : Yes (default)
* Enable extra features           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : No (default)
* Show source tree                : No (For UNIX default)

-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Running cmake hook: BEFORE_SRC_LOAD
-- No hooks registered for BEFORE_SRC_LOAD
-- Running cmake hook: BEFORE_GAME_LIBRARY
-- No hooks registered for BEFORE_GAME_LIBRARY
-- Running cmake hook: AFTER_GAME_LIBRARY
-- No hooks registered for AFTER_GAME_LIBRARY
-- Running cmake hook: AFTER_AUTHSERVER_CMAKE
-- No hooks registered for AFTER_AUTHSERVER_CMAKE
-- Running cmake hook: BEFORE_SCRIPTS_LIBRARY
-- No hooks registered for BEFORE_SCRIPTS_LIBRARY
-- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
-- SCRIPT PREPARATION COMPLETE

-- Running cmake hook: AFTER_WORLDSERVER_CMAKE
-- No hooks registered for AFTER_WORLDSERVER_CMAKE
-- Running cmake hook: AFTER_SRC_LOAD
-- No hooks registered for AFTER_SRC_LOAD
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /usr/bin/clang
CMAKE_CXX_COMPILER= /usr/bin/clang++

-- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Loading module: modules/mod-vas-autobalance-master
-- Running cmake hook: AFTER_LOAD_CONF
-- No hooks registered for AFTER_LOAD_CONF
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/clang
-- Running cmake hook: AFTER_LOAD_CMAKE_MODULES
-- No hooks registered for AFTER_LOAD_CMAKE_MODULES
-- cotire 1.8.0 loaded.
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE headers: /usr/include
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadbclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found git binary : /usr/bin/git

* AzerothCore revision            : 490fd16bf56d+ 2019-05-27 12:09:40 +0000 (master branch)
* AzerothCore buildtype           : Release

* Install core to                 : /usr/local
* Install libraries to            : /usr/local/lib
* Install configs to              : /usr/local/etc

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use unix gperftools             : No  (default)
* Use GIT revision hash           : Yes (default)
* Enable extra features           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : No (default)
* Show source tree                : No (For UNIX default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Looking for MADV_FREE
-- Looking for MADV_FREE - found
-- CXX target common cotired without unity build.
-- Running cmake hook: BEFORE_SRC_LOAD
-- No hooks registered for BEFORE_SRC_LOAD
-- Running cmake hook: BEFORE_GAME_LIBRARY
-- No hooks registered for BEFORE_GAME_LIBRARY
-- CXX target game cotired without unity build.
-- Running cmake hook: AFTER_GAME_LIBRARY
-- No hooks registered for AFTER_GAME_LIBRARY
-- CXX target authserver cotired without unity build.
-- Running cmake hook: AFTER_AUTHSERVER_CMAKE
-- No hooks registered for AFTER_AUTHSERVER_CMAKE
-- Running cmake hook: BEFORE_SCRIPTS_LIBRARY
-- No hooks registered for BEFORE_SCRIPTS_LIBRARY
-- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
-- SCRIPT PREPARATION COMPLETE

-- CXX target scripts cotired without unity build.
-- CXX target worldserver cotired without unity build.
-- Running cmake hook: AFTER_WORLDSERVER_CMAKE
-- No hooks registered for AFTER_WORLDSERVER_CMAKE
-- Running cmake hook: AFTER_SRC_LOAD
-- No hooks registered for AFTER_SRC_LOAD
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wowi/azerothcore/build
`

But ... the mod isn't loaded ... still tried it with naxxramas. No Announcement, no scaling ... nothing. The VASAutoBalance.conf is edited to the values i want (/home/wowi/azerothcore/modules/mod-vas-autobalance-master/conf) ... and still no info in the server-log or something ... what mistake did i made?

**Comment by milestorme** [comment]
That worked it’s installed , do you have both conf files still vas-aitobalamce.vonf.dist and vas-aitobalance.comf

**Comment by milestorme** [comment]
Oh make sure you have .gm off , scaling is ignored if you enter a raid or instance with gm on

**Comment by DogusDE** [comment]
yes, i have both files, but just edited the .conf, not the .conf.dist file. 
Do i have to edit the .conf.dist-file to my values? 
In my understandment the .conf.dist-file is the "template" which isn't used by the server. 

good advice to turn gm off ( i forgot that ), but now i can't enter because of the msg: Your'e not in a raid group ... 

Thats the content of my VASAutoBalance.conf: 

```
[worldserver]

#
###################################################################################################

###################################################################################################
#
# VAS AUTOBALANCE ANNOUNCE
#
#     VASAutoBalanceAnnounce.enable
#        Enable/Disable Autobalance system
#        Default:     1 (1 = ON, 0 = OFF)

VASAutoBalanceAnnounce.enable=1

#
# VAS AUTOBALANCE OPTIONS
#
#     VASAutoBalance.enable
#        Enable/Disable Autobalance system
#        Default:     1 (1 = ON, 0 = OFF)

VASAutoBalance.enable=1

#     VASAutoBalance.InflectionPoint
#        Adjust value of Hyperbolic Tangent function where
#        the curve of scaling must change. A lower value means higher difficulty.
#
#        Example: with 0.5, a creature of raid (40) will have half of its life with 20 players in
#                 with 0.8, the same creature will have half of its life with 12 players in
#
#        Default:     0.5

VASAutoBalance.InflectionPoint=0.8

#     VASAutoBalance.numPlayer
#        Set Server to level of solo mode.
#        Set to 0 to Disable VAS-SOLO Mod.
#        Example: VAS.AutoBalance.XPlayer = 1 will set everything for a 1 player game.
#        Default:     1

VASAutoBalance.numPlayer=3.0

#
#     VASAutoBalance.levelScaling
#        Check the max level of players in map and scale creature based on it
#        0 = Disabled
#        1 = Enabled only in dungeons
#        2 = Always enabled
#        Default:     1

VASAutoBalance.levelScaling=1

#
#     VASAutoBalance.levelHigherOffset
#     VASAutoBalance.levelLowerOffset
#        Level Offsets between creatures will not be scaled by level.
#        You can even use it to disable scaling from lower to higher levelScaling
#        setting levelLowerOffset to 80 (max wotlk level) for example.
#        default: 3 (higher), 0 (lower) 

VASAutoBalance.levelHigherOffset = 3
VASAutoBalance.levelLowerOffset  = 0

#
#     VASAutoBalance.levelUseDbValuesWhenExists
#        When enabled with levelScaling, the creature will use its default database values
#        instead of level scaling formula when player/party level has correspondance with 
#        creature_template minlevel/maxlevel.
#
#        Default:     0 (1 = ON, 0 = OFF)

VASAutoBalance.levelUseDbValuesWhenExists = 0

#
#     VASAutoBalance.LevelEndGameBoost
#        End game creatures have an exponential (not linear) regression
#        that is not correctly handled by db values. Keep this enabled
#        to have stats as near possible to the official ones.
#
#        Default:     1 (1 = ON, 0 = OFF)

VASAutoBalance.LevelEndGameBoost = 1

#
#     VASAutoBalance.Instances
#        Set instances to Auto chance XPlayer depending on players in it.
#        Default:     1 (1 = ON, 0 = OFF)

VASAutoBalance.Instances=1
#
#     VASAutoBalance.DungeonsOnly
#        Only apply scaling changes to dungeons and raids
#        Default:     1 (1 = ON, 0 = OFF)
VASAutoBalance.DungeonsOnly=1

#
#     VASAutoBalance.DebugLevel
#        0 = None
#        1 = Errors Only
#        2 = Errors and Basic Information
#        3 = All VAS Info
#        Default:     2

VASAutoBalance.DebugLevel=2

#
#     VAS.AutoBalance.PlayerChangeNotify
#        Set Auto Notifications to all players in Instance that player count has changed.
#        Default:     1 (1 = ON, 0 = OFF)

VASAutoBalance.PlayerChangeNotify=1

#
#     VASAutoBalance.MinHPModifier
#        Minimum Modifier setting for Health Modification
#        Default:     0.01

VASAutoBalance.MinHPModifier=0.04

#
#     VASAutoBalance.MinDamageModifier
#        Minimum Modifier setting for Damage Modification
#        Default:     0.01

VASAutoBalance.MinDamageModifier=0.3


#
#     VASAutoBalance.rate.*
#        You can tune all rates increasing/decreasing difficulty in a linear way
#        Note that global rate will increase all other rates. For example:
#        global = 2.0 , damage = 1.5  -> it means that damage will be 3.0
#        Default:     1.0

VASAutoBalance.rate.global = 1.0
VASAutoBalance.rate.health = 1.0
VASAutoBalance.rate.mana   = 1.0
VASAutoBalance.rate.armor  = 1.0
VASAutoBalance.rate.damage = 1.0

#
#     VASAutoBalance.playerCountDifficultyOffset
#        Offset of players inside an instance
#        Default:     0

VASAutoBalance.playerCountDifficultyOffset=0

#
#     VASAutoBalance.ForcedIDXX
#        Sets MobIDs for the group they belong to.
#        All 5 Man Mobs should go in VAS.AutoBalance.5.Name
#        All 10 Man Mobs should go in VAS.AutoBalance.10.Name etc.

VASAutoBalance.ForcedID40="11583,16441,30057,13020,15589,14435,18192,14889,14888,14887,14890,15302,15818,15742,15741,15740,18338"
VASAutoBalance.ForcedID25="22997,21966,21965,21964,21806,21215,21845,19728,12397,17711,18256,18192,"
VASAutoBalance.ForcedID20=""
VASAutoBalance.ForcedID10="15689,15550,16152,17521,17225,16028,29324,31099"
VASAutoBalance.ForcedID5="8317,15203,15204,15205,15305,6109,26801,30508,26799,30495,26803,30497,27859,27249"
VASAutoBalance.ForcedID2=""

#
#     VASAutoBalance.DisabledID
#        Disable scaling on specific creatures
#

VASAutoBalance.DisabledID=""

##########################
#
# REWARD SYSTEM (experimental)
#
##########################


#
#   VASAutoBalance.reward.enable
#       This is an experimental feature to reward a player that kill a boss when
#       a pre-wotlk dungeon/raid is completed with creature levelling enabled.
#       This is an idea to boost old contents even if you're end-game player.
#
#       Default:     0 (1 = ON, 0 = OFF)

VASAutoBalance.reward.enable = 0


#
#   VASAutoBalance.reward.raidToken
#   VASAutoBalance.reward.dungeonToken
#
#
#       Default: 
#           raidToken -> emblem of frost (49426)
#           dungeonToken -> emblem of triumph (47241)

VASAutoBalance.reward.raidToken    = 49426
VASAutoBalance.reward.dungeonToken = 47241

#
#   VASAutoBalance.reward.MinPlayerReward
#       This conf option checks how many players are in the same 
#       map before allowing the reward to be carried out
#       if MinPlayerReward is set to two and player is soloing this conf doesn't reward then.
#		this will give more a challenge to players for low level instances.
#
#       Default:     1

VASAutoBalance.reward.MinPlayerReward = 1
# 
```

**Comment by milestorme** [comment]
Yes now go to worldserver.conf and set ignore raid requirements when entering raids

**Comment by DogusDE** [comment]
ok, i've changed the worldserver.conf to that (didn't see that, too), but still ... nothing ... i tried to unbind all instances and join another, just to be sure, but ... no announcement (i've seen, and configured, there should be one in the chat) and no scaling at all. 

btw: thx again ;)

**Comment by milestorme** [comment]
No problems, It’s not a module issue the module works very well on latest core , it’s a configuration issue .
