### ISSUE TITLE
Health multiplyer is incorrect

### ISSUE THREAD

**Issue by talamortis** [azerothcore/mod-vas-autobalance#4]
If 3 players enter an instance the hp of creatures triples. try 3 level 40's in RFK, the creatures have 13k life.

**Comment by Yehonal** [comment]
what instance?

**Comment by talamortis** [comment]
Razorfen Kraul, is the one i found the issue in, others seem to be the same

**Comment by Yehonal** [comment]
I'm working on new formula

**Comment by Yehonal** [comment]
ok i'll write here my research about new scaling formula for health/mana and damage to keep trace of this work.

First of all i've collected data from creature_template using this query that retrieve correct values for damage and health:

```
SET @rank:=0;

SELECT maxlevel,
    ROUND(SUM(health_mod * b.basehp0)/COUNT(*)) AS mid_health,
    ROUND(SUM(`mindmg` + (a.`attackpower` *2.4 / 14)*dmg_multiplier)/COUNT(*)) AS mid_min_damage, 
    ROUND(SUM(`maxdmg` + (a.`attackpower` *2.4 / 14)*dmg_multiplier)/COUNT(*)) AS mid_max_damage
FROM creature_template AS a
LEFT JOIN creature_classlevelstats AS b
ON a.unit_class = b.class AND a.maxlevel = b.level
WHERE rank = @rank AND maxlevel <= 83 AND maxlevel > 1
GROUP BY maxlevel ORDER BY maxlevel LIMIT 10000000
```

After that i've moved those values inside a spreadsheet where i've calculated exponential regression line for damage and health, for both Elite and Normal Creatures

https://docs.google.com/spreadsheets/d/1mIoJ7u7b8rySomF3I7F8qaO7azq1ISZ9BQdRObb_RHw

Now i'm importing this formula in our code and test it.

I'll let you know :)

**Comment by Yehonal** [comment]
please test new formula asap so i can close it eventually

**Comment by Middel** [comment]
The module seems to really solid now. Good Job @Yehonal 
Also the values seem to be correctly. HP / Mana and damage pools.

**Comment by Yehonal** [comment]
Thanks @Middel :) i've released many other improvements. Good Soloing ;D
