### ISSUE TITLE
VAS GM issue.

### ISSUE THREAD

**Issue by Middel** [azerothcore/mod-vas-autobalance#7]
VAS should ignore GM's that both have GameMaster mode ON and are invisible.

i appeared on a player that was solo'ing a instance and reported to cheat within the instance. i appeared on that person. and he knew i was there because VAS told the player that the scaling changed cause someone joined his instance.

Which means VAS triggers as well when a GM joins the instance or appears on a player inside a instance. which kinda defeats the purpose of being invisible as a GM because a player will still know a GM presence is around.

**Comment by Yehonal** [comment]
I'll check asap. For now please try to disable player notify in conf

**Comment by Middel** [comment]
Please fix this :P it makes it almost literally impossible to catch cheaters in instances. because it literally tells the player that a GM has entered their instance.

there must something so you can exclude GM's from showing. i understand we can disable the notifcation but we don't want to do that. because its quite nice for players to know such information. except the part where GM appear on players in instances and it shows we entered the instance. (it doesnt say GM, but it says the name of the person that joined. and when someone isn't grouped with person, and can't see that person. the link is easely made :P)

I understand also there is other priorities such as formulas and such, but i also believe its important for GameMasters to be able to do their job on a server without players knowing they are around. i mean that the purpose of being invisible.

Anyways thank you for your time. i might ask @talamortis to fix this. and maybe he will create a pull request and hopefully you will merge it then as well :) Good job though with the VAS really impressed by it so far.

**Comment by Yehonal** [comment]
Please Test latest commits (update the core too)

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-vas-autobalance/commit/f6af687f1ee5e5001cc8d14ce3ad0eea91df9c64

**Comment by Middel** [comment]
works fine. thanks <3 - Good Stuff!
