### ISSUE TITLE
Possible issue - Seeing phased NPCs after entering dungeon

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-vas-autobalance#9]
I tried this on an azerothcore server using VAS autobalance (but not mine)

I entered ragefire chasm, it said it was set to 1 player difficulty.

Then I left, and I came back to orgrimmar bank on foot (not by teleporting, I don't know if it's important).
There I could see Gamon, and other NPCs in front of the bank on a PLAYER account. These NPCs can only be seen as GM normally.
Then I log out and log back and they have disappeared.

So you can retry the same exact process and see if you get that bug.

**Comment by dunjeon** [comment]
@BarbzYHOOL 
I followed the steps above, and I was unable to reproduce the result.

**Comment by BarbzYHOOL** [comment]
Did you try with gm mode off? I remember I tried this 3 times in a row o_0

It was like the module put me in a phase that only GMs could be in

**Comment by dunjeon** [comment]
I tried it with a player account.

It would be nice to see the .conf file settings thta were used.  Was level scaling on? If so, was it 'dungeon only' or ' always enabled?'

I'm working with the VAS code currently -- adding xp reward scaling based on the amount of creature stat reduction -- I will take a deeper look into the issue you found while I'm at it.

**Comment by BarbzYHOOL** [comment]
It was probably set to default conf.

If not confirmed I'll retry in the future with a cleaner server than my custom one.

PS: you should join the discord!!!!!!

**Comment by dunjeon** [comment]
I finished my VAS work this weekend, and I tested and retested. I was unable to duplicate your result.  I went ahead and captured video if you would like to see my experience.

and about Discord, perhaps =) I have not really done to much with it.

**Comment by BarbzYHOOL** [comment]
Yes, I want to see the video if it's already recorded

And about Discord, yo'ure not the first one to say this (cf stoabrogga) but it's there that some important stuff happen and it's there that I'm the most efficient :P
